/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_postmeta` VALUES
(1,2,"_wp_page_template","default"),
(2,3,"_wp_page_template","default"),
(3,5,"_wp_attached_file","2019/06/themeforest-22551147-kunco-charity-fundraising-wordpress-theme.zip"),
(4,5,"_wp_attachment_context","upgrader"),
(7,7,"_form","<label> Your Name (required)\n    [text* your-name] </label>\n\n<label> Your Email (required)\n    [email* your-email] </label>\n\n<label> Subject\n    [text your-subject] </label>\n\n<label> Your Message\n    [textarea your-message] </label>\n\n[submit \"Send\"]"),
(8,7,"_mail","a:8:{s:7:\"subject\";s:47:\"Tigray Development Association \"[your-subject]\"\";s:6:\"sender\";s:54:\"Tigray Development Association <wordpress@tdana.local>\";s:4:\"body\";s:187:\"From: [your-name] <[your-email]>\nSubject: [your-subject]\n\nMessage Body:\n[your-message]\n\n-- \nThis e-mail was sent from a contact form on Tigray Development Association (http://tdana.local)\";s:9:\"recipient\";s:18:\"elsaadik@yahoo.com\";s:18:\"additional_headers\";s:22:\"Reply-To: [your-email]\";s:11:\"attachments\";s:0:\"\";s:8:\"use_html\";i:0;s:13:\"exclude_blank\";i:0;}"),
(9,7,"_mail_2","a:9:{s:6:\"active\";b:0;s:7:\"subject\";s:47:\"Tigray Development Association \"[your-subject]\"\";s:6:\"sender\";s:54:\"Tigray Development Association <wordpress@tdana.local>\";s:4:\"body\";s:129:\"Message Body:\n[your-message]\n\n-- \nThis e-mail was sent from a contact form on Tigray Development Association (http://tdana.local)\";s:9:\"recipient\";s:12:\"[your-email]\";s:18:\"additional_headers\";s:28:\"Reply-To: elsaadik@yahoo.com\";s:11:\"attachments\";s:0:\"\";s:8:\"use_html\";i:0;s:13:\"exclude_blank\";i:0;}"),
(10,7,"_messages","a:8:{s:12:\"mail_sent_ok\";s:45:\"Thank you for your message. It has been sent.\";s:12:\"mail_sent_ng\";s:71:\"There was an error trying to send your message. Please try again later.\";s:16:\"validation_error\";s:61:\"One or more fields have an error. Please check and try again.\";s:4:\"spam\";s:71:\"There was an error trying to send your message. Please try again later.\";s:12:\"accept_terms\";s:69:\"You must accept the terms and conditions before sending your message.\";s:16:\"invalid_required\";s:22:\"The field is required.\";s:16:\"invalid_too_long\";s:22:\"The field is too long.\";s:17:\"invalid_too_short\";s:23:\"The field is too short.\";}"),
(11,7,"_additional_settings",NULL),
(12,7,"_locale","en_US"),
(13,11,"_wp_attached_file","woocommerce-placeholder.png"),
(14,11,"_wp_attachment_metadata","a:5:{s:5:\"width\";i:1200;s:6:\"height\";i:1200;s:4:\"file\";s:27:\"woocommerce-placeholder.png\";s:5:\"sizes\";a:6:{s:9:\"thumbnail\";a:4:{s:4:\"file\";s:35:\"woocommerce-placeholder-180x180.png\";s:5:\"width\";i:180;s:6:\"height\";i:180;s:9:\"mime-type\";s:9:\"image/png\";}s:6:\"medium\";a:4:{s:4:\"file\";s:35:\"woocommerce-placeholder-750x510.png\";s:5:\"width\";i:750;s:6:\"height\";i:510;s:9:\"mime-type\";s:9:\"image/png\";}s:12:\"medium_large\";a:4:{s:4:\"file\";s:35:\"woocommerce-placeholder-768x768.png\";s:5:\"width\";i:768;s:6:\"height\";i:768;s:9:\"mime-type\";s:9:\"image/png\";}s:5:\"large\";a:4:{s:4:\"file\";s:37:\"woocommerce-placeholder-1024x1024.png\";s:5:\"width\";i:1024;s:6:\"height\";i:1024;s:9:\"mime-type\";s:9:\"image/png\";}s:14:\"post-thumbnail\";a:4:{s:4:\"file\";s:35:\"woocommerce-placeholder-550x550.png\";s:5:\"width\";i:550;s:6:\"height\";i:550;s:9:\"mime-type\";s:9:\"image/png\";}s:12:\"kunco_medium\";a:4:{s:4:\"file\";s:35:\"woocommerce-placeholder-780x550.png\";s:5:\"width\";i:780;s:6:\"height\";i:550;s:9:\"mime-type\";s:9:\"image/png\";}}s:10:\"image_meta\";a:12:{s:8:\"aperture\";s:1:\"0\";s:6:\"credit\";s:0:\"\";s:6:\"camera\";s:0:\"\";s:7:\"caption\";s:0:\"\";s:17:\"created_timestamp\";s:1:\"0\";s:9:\"copyright\";s:0:\"\";s:12:\"focal_length\";s:1:\"0\";s:3:\"iso\";s:1:\"0\";s:13:\"shutter_speed\";s:1:\"0\";s:5:\"title\";s:0:\"\";s:11:\"orientation\";s:1:\"0\";s:8:\"keywords\";a:0:{}}}"),
(15,1,"dpsp_networks_shares","a:1:{s:9:\"pinterest\";i:0;}"),
(16,1,"dpsp_networks_shares_total","0"),
(17,1,"dpsp_networks_shares_last_updated","1559774553"),
(18,5,"_oembed_8af782d8daa5efd7d23830632c847a7d","{{unknown}}"),
(19,2,"_edit_lock","1559776462:1");
